
name: drug-screening-pipeline

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - pandas
  - numpy
  - matplotlib
  # Molecular screening
  - rdkit
  - vina
  - openbabel
  - meeko